<?php if(Mage::helper('tagalys_core')->isTagalysModuleEnabled('search_suggestions') || Mage::helper('tagalys_core')->isTagalysModuleEnabled('search') || Mage::helper('tagalys_core')->isTagalysModuleEnabled('mpages') || Mage::helper('tagalys_core')->isTagalysModuleEnabled('similar_products')): ?>
    <?php
        $eventDetails = false;
        try {
            $eventDetails = array(
                'action' => 'view',
                'sku' => $this->getProduct()->getSku()
            );
        } catch (Exception $e) {
            // don't log this as it might happen too often
        }
    ?>
    <?php if ($eventDetails != false): ?>
        <script>
            try {
                (function( $ ) {
                    $(function() {
                        try {
                            $.fn.tagalys_analytics.track_event('product_action', <?php echo json_encode($eventDetails) ?>);
                        }
                        catch(err) {
                            
                        }
                    });
                }( jQuery ));
            }
            catch(err) {
                
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
