<?php 
$helper = Mage::helper('tagalys_core');
	// $html = str_get_html($helper->getTagalysConfig('merchandising_page_template'));

	// $html->find('h1')->innertext = "Merchandising Page";

	// var_dump($this->getVariable('res'));

$service = Mage::helper("merchandisingpage");
$res = $service->getTagalysSearchData();
	// var_dump($res);

$html = $helper->getTagalysConfig('merchandising_page_template');

$html = str_replace("{{title}}", isset($res['name']) ? $res['name'] : ""  , $html);
$html = str_replace("{{description}}", isset($res['variables']['description']) ? $res['variables']['description'] : "", $html);
$html = str_replace("{{banner_image_url}}", isset($res['variables']['banner_image_url']) ? $res['variables']['banner_image_url'] : "", $html);

echo $html;
?>